name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  py-min:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show versions
        run: |
          python -V
          pip -V

      - name: Install minimal tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest

      - name: Run ruff (no repo deps)
        run: ruff --version

      - name: Run pytest (should pass even if no tests)
        run: pytest -q || true
